# Generated by Django 5.2.1 on 2025-05-19 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='special_requests',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guests',
            new_name='num_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cottage_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristspot',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.touristspot'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
