# Generated by Django 5.2.1 on 2025-05-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_profile_sex_alter_reservation_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'Regular User'), ('OFFICIAL', 'Tourism Management Official')], default='USER', max_length=10),
        ),
    ]
