# Generated by Django 5.2.1 on 2025-05-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_remove_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='price',
        ),
    ]
