# Generated by Django 5.2.1 on 2025-05-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_remove_touristspot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
