# Generated by Django 5.2.1 on 2025-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_touristspot_image_alter_touristspot_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='is_limited',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='type',
            field=models.CharField(choices=[('beach', 'Beach'), ('falls', 'Falls'), ('islet', 'Islet'), ('other', 'Other')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(upload_to='tourist_spot_images/'),
        ),
    ]
