# Generated by Django 5.2.1 on 2025-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_reservation_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='type',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
    ]
