# Generated by Django 5.2.1 on 2025-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_remove_reservation_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='cottage_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
