# Generated by Django 5.2.1 on 2025-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_touristspot_cottage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='cottage_price',
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tourist_spot_images/'),
        ),
    ]
