# Generated by Django 5.2.1 on 2025-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_remove_touristspot_cottage_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='cottage_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
