# Generated by Django 5.2.1 on 2025-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_touristspot_cottage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='is_limited',
            field=models.PositiveIntegerField(blank=True, help_text='Set a number limit for bookings per day (leave blank for unlimited)', null=True),
        ),
    ]
