# Generated by Django 5.2.1 on 2025-05-26 15:57

import tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_alter_touristspot_is_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='time_closed',
            field=models.TimeField(default=tourism.models.default_close_time),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='time_open',
            field=models.TimeField(default=tourism.models.default_open_time),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
