# Generated by Django 5.2.1 on 2025-05-27 02:24

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_touristspot_time_closed_touristspot_time_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='available_until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
